{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: ea3779f157a7efe82d0e10a59af64440e34b5e8004eaee08d7d61bbb889701fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-api >=1.12,<2.0
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-instrumentation-wsgi =={{ version }}
    - opentelemetry-semantic-conventions =={{ version }}
    - opentelemetry-util-http =={{ version }}
    - packaging >=21.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    - flask >=1.0,<3.0
    - werkzeug <3.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.flask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
