{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: ea3779f157a7efe82d0e10a59af64440e34b5e8004eaee08d7d61bbb889701fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.43b0
    - opentelemetry-instrumentation ==0.43b0
    - opentelemetry-semantic-conventions ==0.43b0
    - opentelemetry-util-http ==0.43b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0
    # - werkzeug <3.0.0
    # - packaging >=21.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.1.2
    # - flask <3.0,>=1.0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
