{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: 8b379d331b61f40a7c72c9ae8e0fca72c72ffeb6db75908811217196c9544b9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.59b0
    - opentelemetry-instrumentation-wsgi ==0.59b0
    - opentelemetry-semantic-conventions ==0.59b0
    - opentelemetry-util-http ==0.59b0
    - packaging >=21.0
    - flask >=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.flask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
