{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.47b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: f8cf6a3c740344edd3077ee8560495c548989851264b6cbcdd4b4947bc7cb33e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.47b0
    - opentelemetry-instrumentation-wsgi ==0.47b0
    - opentelemetry-semantic-conventions ==0.47b0
    - opentelemetry-util-http ==0.47b0
    - packaging >=21.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    - flask >=1.0
    - werkzeug <3.0.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.1.2
    # - importlib-metadata >=4.0
    # - importlib-metadata >=4.0
    # - importlib-metadata >=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.flask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
