{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.54b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: 5246eea19a8ac004c5bdb24c62929e38097835f12aae53ea983dac6b38a94133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.54b0
    - opentelemetry-instrumentation-wsgi ==0.54b0
    - opentelemetry-semantic-conventions ==0.54b0
    - opentelemetry-util-http ==0.54b0
    - packaging >=21.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    - flask >=1.0
    - werkzeug <3.0.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.1.2
    # - importlib-metadata >=4.0
    # - importlib-metadata >=4.0
    # - importlib-metadata >=4.0
    # - importlib-metadata >=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.flask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
